In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r'C:\Users\jchu\OneDrive - San Diego Association of Governments\Projects\2023\Series 15 Subregional Forecast\2023-089 PopSim- Series 15 Subregional Baseline Forecast\Data'
persons = {}
households = {}
years = [2026, 2029, 2032, 2035, 2040, 2050]

In [3]:
for year in years:
    persons['v9_{}'.format(year)] = pd.read_csv(path+r'\version9\synthetic_persons_{}.csv'.format(year)).fillna('NA')
    households['v9_{}'.format(year)] = pd.read_csv(path+r'\version9\synthetic_households_{}.csv'.format(year)).fillna('NA')
    

    persons['v10_{}'.format(year)] = pd.read_csv(path+r'\version10\synthetic_persons_{}.csv'.format(year)).fillna('NA')
    households['v10_{}'.format(year)] = pd.read_csv(path+r'\version10\synthetic_households_{}.csv'.format(year)).fillna('NA')

In [17]:
for year in years:
    print('CHECK FOR YEAR: ' + str(year))
    print('persons check')
    print((persons['v9_{}'.format(year)].sort_values(['mgra', 'household_id', 'SERIALNO', 'SPORDER']).reset_index(drop=True) != persons['v10_{}'.format(year)].sort_values(['mgra', 'household_id', 'SERIALNO', 'SPORDER']).reset_index(drop=True)).sum().sum())
    print('households_check')
    print((households['v9_{}'.format(year)][['household_id', 'mgra', 'SERIALNO', 'NP', 'HHADJINC', 'HHT', 'HUPAC', 'VEH', 'BLD']] != households['v10_{}'.format(year)][['household_id', 'mgra', 'SERIALNO', 'NP', 'HHADJINC', 'HHT', 'HUPAC', 'VEH', 'BLD']]).sum().sum())
    print('gq_check')
    print(((households['v9_{}'.format(year)]['TYPEHUGQ']==1) != (households['v10_{}'.format(year)]['gq_type']==0)).sum())
    print('workers_check')
    workers_check = persons['v10_{}'.format(year)][persons['v10_{}'.format(year)]['ESR'].isin([1, 2, 4, 5])].groupby('household_id').count()['mgra'].reset_index().merge(households['v10_{}'.format(year)][['household_id', 'workers']], on='household_id', how='left')
    workers_check['diff'] = workers_check['mgra'] - workers_check['workers']
    print(workers_check['diff'].sum())
    print(persons['v10_{}'.format(year)][~persons['v10_{}'.format(year)]['household_id'].isin(workers_check['household_id'])]['ESR'].unique())
    print('-'*26)

CHECK FOR YEAR: 2026
persons check
0
households_check
0
gq_check
0
workers_check
0
[6. 0. 3.]
--------------------------
CHECK FOR YEAR: 2029
persons check
0
households_check
0
gq_check
0
workers_check
0
[6. 0. 3.]
--------------------------
CHECK FOR YEAR: 2032
persons check
0
households_check
0
gq_check
0
workers_check
0
[6. 0. 3.]
--------------------------
CHECK FOR YEAR: 2035
persons check
0
households_check
0
gq_check
0
workers_check
0
[6. 0. 3.]
--------------------------
CHECK FOR YEAR: 2040
persons check
0
households_check
0
gq_check
0
workers_check
0
[6. 3. 0.]
--------------------------
CHECK FOR YEAR: 2050
persons check
0
households_check
0
gq_check
0
workers_check
0
[6. 0. 3.]
--------------------------


In [6]:
workers_households = {}
for year in years:
    workers_households[year] = households['v10_{}'.format(year)].groupby('gq_type')['workers'].sum()
workers_households

{2026: gq_type
 0    1526266
 1      40766
 2       5399
 3       3792
 Name: workers, dtype: int64,
 2029: gq_type
 0    1541558
 1      41075
 2       5430
 3       3804
 Name: workers, dtype: int64,
 2032: gq_type
 0    1558781
 1      41554
 2       5489
 3       3836
 Name: workers, dtype: int64,
 2035: gq_type
 0    1577471
 1      42074
 2       5570
 3       3886
 Name: workers, dtype: int64,
 2040: gq_type
 0    1607231
 1      41850
 2       5534
 3       3872
 Name: workers, dtype: int64,
 2050: gq_type
 0    1630336
 1      41181
 2       5464
 3       3682
 Name: workers, dtype: int64}

# Workers by Household Type

In [8]:
pd.DataFrame(workers_households).T

gq_type        0      1     2     3
2026     1526266  40766  5399  3792
2029     1541558  41075  5430  3804
2032     1558781  41554  5489  3836
2035     1577471  42074  5570  3886
2040     1607231  41850  5534  3872
2050     1630336  41181  5464  3682