In [2]:
import numpy as np
import pandas as pd

In [7]:
persons =pd.read_csv('synthetic_persons.csv') # focus on persons
persons.head()

tract  mgra  household_id  SPORDER  AGEP  SEX  ESR  COW  WKHP  SCHG  \
0  18100.0   245             1        1    52    2  1.0  1.0  40.0   NaN   
1  18100.0   245             1        2    39    1  3.0  1.0  40.0   NaN   
2  18100.0   245             1        3    79    2  6.0  NaN   NaN   NaN   
3  18100.0   245             2        1    25    2  4.0  5.0  50.0  15.0   
4  18100.0   245             2        2    24    1  1.0  6.0  20.0  15.0   

   RAC1P  HISP  MIL  isWorker  
0      1     2  4.0         1  
1      1     2  4.0         0  
2      1     2  4.0         0  
3      6     2  1.0         1  
4      1     1  2.0         1

In [8]:
households=pd.read_csv('synthetic_households.csv')
households.head()


household_id    tract  mgra  NP  HHADJINC   ADJINC  HHT  WIF  HUPAC  VEH  \
0             1  18100.0   245   3  121500.0  1010145  3.0  2.0    4.0  3.0   
1             2  18100.0   245   3   75400.0  1010145  1.0  2.0    1.0  2.0   
2             3  18100.0   245   3   45800.0  1010145  3.0  1.0    4.0  1.0   
3             4  18100.0   245   3   70000.0  1010145  1.0  2.0    1.0  2.0   
4             5  18100.0   245   1   35700.0  1010145  6.0  NaN    4.0  1.0   

   numWorkers  GQ_type  
0         1.0      NaN  
1         2.0      NaN  
2         1.0      NaN  
3         2.0      NaN  
4         1.0      NaN

In [13]:
no_working = persons[(np.isnan(persons['ESR'])) | (persons['ESR'] == 3) | (persons['ESR'] == 6)]
no_working

tract   mgra  household_id  SPORDER  AGEP  SEX  ESR  COW  WKHP  \
1        18100.0    245             1        2    39    1  3.0  1.0  40.0   
2        18100.0    245             1        3    79    2  6.0  NaN   NaN   
5        18100.0    245             2        3     4    2  NaN  NaN   NaN   
7        18100.0    245             3        2    22    2  6.0  NaN   NaN   
8        18100.0    245             3        3    66    2  6.0  NaN   NaN   
...          ...    ...           ...      ...   ...  ...  ...  ...   ...   
3356963      NaN  24280       1262831        1    47    1  6.0  NaN   NaN   
3356964      NaN  24280       1262832        1    55    2  6.0  NaN   NaN   
3356965      NaN  24280       1262833        1    94    2  6.0  NaN   NaN   
3356966      NaN  24280       1262834        1    68    1  6.0  NaN   NaN   
3356967      NaN  24280       1262835        1    38    1  6.0  1.0   NaN   

         SCHG  RAC1P  HISP  MIL  isWorker  
1         NaN      1     2  4.0         0  
2         NaN      1     2  4.0         0  
5         1.0      6     2  NaN         0  
7         NaN      1     1  4.0         0  
8         NaN      1     1  4.0         0  
...       ...    ...   ...  ...       ...  
3356963   NaN      2     1  4.0         0  
3356964   NaN      3     1  4.0         0  
3356965   NaN      2     1  4.0         0  
3356966   NaN      1     1  2.0         0  
3356967   NaN      1     2  4.0         0  

[1800495 rows x 14 columns]

In [14]:
no_working['isWorker'].unique() 

array([0], dtype=int64)

In [16]:
less_than_16 = persons[(np.isnan(persons['ESR']))]
less_than_16

tract   mgra  household_id  SPORDER  AGEP  SEX  ESR  COW  WKHP  \
5        18100.0    245             2        3     4    2  NaN  NaN   NaN   
11       18100.0    245             4        3     5    2  NaN  NaN   NaN   
16       18100.0    245             7        3     1    1  NaN  NaN   NaN   
19       18100.0    245             8        3    10    2  NaN  NaN   NaN   
20       18100.0    245             8        4     9    1  NaN  NaN   NaN   
...          ...    ...           ...      ...   ...  ...  ...  ...   ...   
3356842      NaN  24280       1262710        1    13    1  NaN  NaN   NaN   
3356861      NaN  24280       1262729        1    13    1  NaN  NaN   NaN   
3356896      NaN  24280       1262764        1    13    1  NaN  NaN   NaN   
3356900      NaN  24280       1262768        1    13    1  NaN  NaN   NaN   
3356938      NaN  24280       1262806        1    13    1  NaN  NaN   NaN   

         SCHG  RAC1P  HISP  MIL  isWorker  
5         1.0      6     2  NaN         0  
11        2.0      1     3  NaN         0  
16        NaN      3     2  NaN         0  
19        7.0      1     1  NaN         0  
20        6.0      1     1  NaN         0  
...       ...    ...   ...  ...       ...  
3356842  10.0      1     1  NaN         0  
3356861  10.0      1     1  NaN         0  
3356896  10.0      1     1  NaN         0  
3356900  10.0      1     1  NaN         0  
3356938  10.0      1     1  NaN         0  

[699147 rows x 14 columns]

In [21]:
(less_than_16['AGEP']<16).all()

True

In [23]:
(less_than_16['COW']).unique()

array([nan])

In [26]:
persons[(persons['ESR'] == 3) | (persons['ESR'] == 6)]['isWorker'].unique()

array([0], dtype=int64)

In [31]:
persons[(persons['ESR'] == 3) | (persons['ESR'] == 6)]['COW'].unique()

array([ 1., nan,  6.,  3.,  2.,  4.,  9.,  7.,  5.,  8.])

In [34]:
persons[(persons['ESR'] == 3) | (persons['ESR'] == 6)].to_csv('esr_3_6_#5.csv')

In [41]:
persons[(persons['ESR'] == 2) | (persons['ESR'] == 5)]['WKHP'].max()

99.0

In [45]:
persons[(persons['ESR'] == 4) | (persons['ESR'] == 5)]['MIL'].unique()

array([1., 3.])

In [52]:
persons[~((np.isnan(persons['MIL'])) | (persons['MIL'] == 4))]['COW'].unique()

array([ 5.,  6.,  1., nan,  2.,  7.,  3.,  4.,  8.,  9.])

In [ ]:
persons[(persons['ESR'] == 4) | (persons['ESR'] == 5)]['MIL']